name: CORE Continuous Testing Pipeline

on: [push, workflow_dispatch, workflow_call]

jobs:
  init_test_sequence:
    name: Initiate Tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
